dotfiles_repo: "https://github.com/edgester/dotfiles.git"
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: "~/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .bashrc.d
  - .gitignore
  - .vimrc
flatpak_method: system
flatpak_packages:
  - io.neovim.nvim
  - org.kiwix.desktop 
  - org.zealdocs.Zeal
