---
roles:
  - src: crivetimihai.bootstrap
  - src: https://github.com/edgester/flatpak.git
    version: main
    scm: git
    name: edgester.flatpak
  - src: crivetimihai.hashicorp
  - src: geerlingguy.dotfiles
  - src: webarchitect609.skype
    name: skype
  - src: freedomofpress.signal-desktop
    name: signal-desktop
  - src: https://github.com/edgester/ansible-role-vagrant_libvirt.git
    version: main
    scm: git
    name: vagrant_libvirt

collections:
  - name: elreydetoda.virtualization
  - name: community.general
