---
- name: Configure laptop
  hosts:
    - all

  vars:
    vagrant_version: 2.2.14

  pre_tasks:

    - name: Load OS variables
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - "{{ansible_distribution|lower}}.yml"
            - "{{ansible_os_family|lower}}.yml"
            - default.yaml
          paths:
            - 'vars'
      tags: [always]

    - name: Update apt cache if needed
      apt:
        cache_valid_time: 3600
      become: yes
      when: ansible_os_family|lower == 'debian'
      tags: [always]

    - name: Install pre-requisite packages
      package:
        name:
          - git
      become: true
      tags: [always]

  roles:
    - edgester.flatpak

    - role: crivetimihai.bootstrap
      become: yes

    - role: geerlingguy.dotfiles
      tags: [dotfiles]

    - role: skype
      when: ansible_os_family|lower == 'debian'
      become: yes

    - role: signal-desktop
      become: yes
      when: ansible_os_family|lower == 'debian'

    - role: elreydetoda.virtualization.kvm
      when: ansible_os_family|lower == 'debian'

    - role: elreydetoda.virtualization.vagrant
      when: ansible_os_family|lower == 'debian'

    - role: vagrant_libvirt
      when: ansible_os_family|lower == 'debian'

  tasks:
    - name: Add obs studio PPA and key
      apt_repository:
        repo: ppa:obsproject/obs-studio
      become: yes
      when: ansible_os_family|lower == 'debian'

    - name: Check if powertools is enabled
      ansible.builtin.shell: "dnf repolist | grep -qs powertools"
      failed_when: false
      when: ansible_os_family|lower == 'redhat'
      register: dnf_powertools

    - name: Enable powertools repo on Red Hat family
      ansible.builtin.command: "dnf config-manager --set-enabled powertools"
      become: yes
      when:
        - dnf_powertools.rc != 0
        - ansible_os_family|lower == 'redhat'

    - name: Install OS packages
      package:
        name: "{{ package_list }}"
        state: present
      become: yes

    - name: Run dotfiles pre-flight script
      command: ~/dotfiles/pre-flight
      register: dotfiles_preflight
      tags: [dotfiles]

    - name: ~/dotfiles/pre-flight output
      debug:
        var: dotfiles_preflight.stdout_lines
      tags: [dotfiles]

    - name: Run dotfiles run script
      command: ~/dotfiles/run
      register: dotfiles_run
      tags: [dotfiles]

    - name: ~/dotfiles/run output
      debug:
        var: dotfiles_run.stdout_lines
      tags: [dotfiles]
