---
- name: Configure laptop
  hosts:
    - all

  vars:
    vagrant_version: 2.2.14

  pre_tasks:
    - name: Update apt cache if needed
      apt:
        cache_valid_time: 3600
      become: yes

  roles:
    - edgester.flatpak
    - role: crivetimihai.bootstrap
      become: yes
    - role: geerlingguy.dotfiles
    - role: skype
      become: yes
    - role: signal-desktop
      become: yes
    - vagrant_libvirt

  tasks:
    - name: Install github cli
      include_tasks: gh_cli.yml

    - name: source bashrc.d in bashrc
      lineinfile:
        path: ~/.bashrc
        line: "[ -f ~/.bashrc.d/bashrc.init ] && source ~/.bashrc.d/bashrc.init"

    - name: Add obs studio PPA and key
      apt_repository:
        repo: ppa:obsproject/obs-studio
      become: yes

    - name: Install apt packages
      apt:
        name:
          - ansible
          - ffmpeg
          - fonts-powerline
          - fzf
          - git
          - git-lfs
          - golang
          - jq
          - obs-studio
          - rclone
          - snapd
          - thunderbird
          - tig
          - vim
        state: present
      become: true

    - name: Run dotfiles run script
      command: ~/dotfiles/run
      register: dotfiles_run

    - name: ~/dotfiles/run output
      debug:
        var: dotfiles_run.stdout_lines
