---
- name: Configure laptop
  hosts:
    - all

  pre_tasks:
    - name: Update apt cache if needed
      apt:
        cache_valid_time: 3600
      become: yes

  roles:
      #- crivetimihai.anaconda
    - edgester.flatpak
    - role: crivetimihai.bootstrap
      become: yes
        #- crivetimihai.docker
        # - crivetimihai.hashicorp
        # - crivetimihai.kvm
    - role: geerlingguy.dotfiles
    - role: skype
      become: yes

  tasks:
    - name: Install github cli
      include_tasks: gh_cli.yml

    - name: source bashrc.d in bashrc
      lineinfile:
        path: ~/.bashrc
        line: "[ -f ~/.bashrc.d/bashrc.init ] && source ~/.bashrc.d/bashrc.init"

    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        - fonts-powerline
        - fzf
        - git
        - golang
        - jq
        - rclone
        - snapd
        - thunderbird
        - vim
