---
- name: Configure laptop
  hosts:
    - all

  roles:
      #- crivetimihai.anaconda
    - edgester.flatpak
    - role: crivetimihai.bootstrap
      become: yes
        #- crivetimihai.docker
        # - crivetimihai.hashicorp
        # - crivetimihai.kvm
    - role: geerlingguy.dotfiles

  tasks:
    - name: source bashrc.d in bashrc
      lineinfile:
        path: ~/.bashrc
        line: "[ -f ~/.bashrc.d/bashrc.init ] && source ~/.bashrc.d/bashrc.init"
