---
- name: Configure laptop
  hosts:
    - all

  vars:
    vagrant_version: 2.2.14

  pre_tasks:

    - name: Load OS variables
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - "{{ansible_distribution|lower}}.yml"
            - "{{ansible_os_family|lower}}.yml"
            - default.yaml
          paths:
            - 'vars'

    - name: Update apt cache if needed
      apt:
        cache_valid_time: 3600
      become: yes
      when: ansible_os_family|lower == 'debian'

    - name: Install pre-requisite packages
      package:
        name:
          - git
      become: true

  roles:
    - edgester.flatpak

    - role: crivetimihai.bootstrap
      become: yes

    - role: skype
      when: ansible_os_family|lower == 'debian'
      become: yes

    - role: signal-desktop
      become: yes
      when: ansible_os_family|lower == 'debian'

    - role: elreydetoda.virtualization.kvm
      when: ansible_os_family|lower == 'debian'

    - role: elreydetoda.virtualization.vagrant
      when: ansible_os_family|lower == 'debian'

    - role: vagrant_libvirt
      when: ansible_os_family|lower == 'debian'

  tasks:
    - name: Add obs studio PPA and key
      apt_repository:
        repo: ppa:obsproject/obs-studio
      become: yes
      when: ansible_os_family|lower == 'debian'

    - name: Install OS packages
      package:
        name: "{{ package_list }}"
        state: present
      become: yes

    - name: Run dotfiles run script
      command: ~/dotfiles/run
      register: dotfiles_run

    - name: ~/dotfiles/run output
      debug:
        var: dotfiles_run.stdout_lines
