---
- name: Configure laptop
  hosts:
    - all

  vars:
    vagrant_version: 2.2.14

  pre_tasks:

    - name: Update apt cache if needed
      apt:
        cache_valid_time: 3600
      become: yes
      when: ansible_os_family|lower == 'debian'

    - name: Install pre-requisite packages
      package:
        name:
          - git
      become: true

  roles:
    - edgester.flatpak

    - role: crivetimihai.bootstrap
      become: yes

    - role: geerlingguy.dotfiles

    - role: skype
      when: ansible_os_family|lower == 'debian'
      become: yes

    - role: signal-desktop
      become: yes
      when: ansible_os_family|lower == 'debian'

    - role: elreydetoda.virtualization.kvm
      when: ansible_os_family|lower == 'debian'

    - role: elreydetoda.virtualization.vagrant
      when: ansible_os_family|lower == 'debian'

    - role: vagrant_libvirt
      when: ansible_os_family|lower == 'debian'

  tasks:
    - name: Install github cli
      include_tasks: gh_cli.yml

    - name: source bashrc.d in bashrc
      lineinfile:
        path: ~/.bashrc
        line: "[ -f ~/.bashrc.d/bashrc.init ] && source ~/.bashrc.d/bashrc.init"

    - name: Add obs studio PPA and key
      apt_repository:
        repo: ppa:obsproject/obs-studio
      become: yes
      when: ansible_os_family|lower == 'debian'

    - name: Install OS packages
      package:
        name:
          - ansible
          - git
          - git-lfs
          - golang
          - jq
          - rclone
          - snapd
          - thunderbird
          - tig
          - virt-manager
          - virt-viewer
      become: yes

    - name: Install apt packages
      apt:
        name:
          - ffmpeg
          - fonts-powerline
          - fzf
          - libreoffice
          - obs-studio
          - spice-client-gtk
          - vim
        state: present
      become: yes
      when: ansible_os_family|lower == 'debian'

    - name: Run dotfiles run script
      command: ~/dotfiles/run
      register: dotfiles_run

    - name: ~/dotfiles/run output
      debug:
        var: dotfiles_run.stdout_lines
